### ISSUE TITLE
DISCONNECTED_INBOUND

### ISSUE THREAD

**Issue by tverma1** [christiandelbianco/monitor-table-change-with-sqltabledependency#45]
Is there a way to clean up the que status after messages have been processed by sqltabledependency?  The following query shows the conversation state as DISCONNECTED_INBOUND for all messages, and it stays that way until the .Net program is terminated:

select  lifetime, state_desc, security_timestamp from sys.conversation_endpoints;

**Comment by christiandelbianco** [comment]
Hi, which version are you using?
This issues is fixed starting from version 6.0

**Comment by tverma1** [comment]
hi, I am using SqlTableDependency version 6.1.0 and still see the DISCONNECTED_INBOUND status message.

**Comment by christiandelbianco** [comment]
Ok...then i need more info about where do you uuse sqltabledependency and how you use it
